### ISSUE TITLE
Add context manager

### ISSUE THREAD

**Issue by BaboucheOne** [BaboucheOne/BuggyBot#4]
In the directory ./bot/config/context, add all the necessary files to create a bot based on different configurations. For example, we will need a different MongoDB address when using it in production than in debugging.

To achieve this, we can create an argument reader in main.py that accepts an argument --env prod or --env dev. The default one is --env prod, meaning it's not a mandatory argument. Therefore, if the argument is not provided, use the production configuration.

For now, the script will require adding a field for the MongoDB production in the .env file.

**Comment by Davidferl** [comment]
put Marc on this task
